config: !!python/object:src.ml.tft.model.TFTConfig
  dropout: 0.1
  hidden_dim: 64
  horizons:
  - 30
  - 45
  - 60
  input_dim: 15
  learning_rate: 0.001
  lookback_window: 60
  num_encoder_layers: 2
  num_heads: 4
  quantiles:
  - 0.1
  - 0.5
  - 0.9
  weight_decay: 1.0e-05
